// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBixwQneexd8rLwCJTTpGyLjG-JTssM5Ik',
    appId: '1:717642421261:web:a61c6e4338475740d2b144',
    messagingSenderId: '717642421261',
    projectId: 'heartlink-56780',
    authDomain: 'heartlink-56780.firebaseapp.com',
    storageBucket: 'heartlink-56780.firebasestorage.app',
    measurementId: 'G-J1JRE5BN9C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBawGSyqvAySd7pXS0QNZMCoylarmSIoJA',
    appId: '1:717642421261:android:dc815af4cec913b0d2b144',
    messagingSenderId: '717642421261',
    projectId: 'heartlink-56780',
    storageBucket: 'heartlink-56780.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCC0vEUcIfEFJHb2AJTq3eZsMFNBJdsYJQ',
    appId: '1:717642421261:ios:c93be3b75a23dce0d2b144',
    messagingSenderId: '717642421261',
    projectId: 'heartlink-56780',
    storageBucket: 'heartlink-56780.firebasestorage.app',
    iosBundleId: 'com.example.heartLinkApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCC0vEUcIfEFJHb2AJTq3eZsMFNBJdsYJQ',
    appId: '1:717642421261:ios:c93be3b75a23dce0d2b144',
    messagingSenderId: '717642421261',
    projectId: 'heartlink-56780',
    storageBucket: 'heartlink-56780.firebasestorage.app',
    iosBundleId: 'com.example.heartLinkApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBixwQneexd8rLwCJTTpGyLjG-JTssM5Ik',
    appId: '1:717642421261:web:b303c0e1cc37884cd2b144',
    messagingSenderId: '717642421261',
    projectId: 'heartlink-56780',
    authDomain: 'heartlink-56780.firebaseapp.com',
    storageBucket: 'heartlink-56780.firebasestorage.app',
    measurementId: 'G-K0PBWT9KS7',
  );
}
